/// Human readable messages for error codes.
const errorsKKM = {
  'unknown_error_code': 'Unknown error',
  'protection_key_not_found':
      'Protection key not found / license not entered / license invalid',
  'port_blocked': 'Port is blocked',
  'port_not_open': 'Port not open',
  'failed_to_connect_to_server': 'Failed to connect to server',
  'cannot_change_baudrate_in_trk':
      'Cannot change baud rate when working through the TRK control unit',
  'cannot_remove_active_logical_device':
      'Cannot remove an active logical device',
  'check_subtotal_not_changed': 'Check subtotal did not change',
  'not_supported_in_this_driver_version':
      'Not supported in this driver version',
  'protocol_error': 'Protocol error',
  'invalid_logical_device_number': 'Invalid logical device number',
  'parameter_out_of_range': 'Parameter out of range',
  'unrecognized_error': 'Unrecognized error',
  'invalid_response_length': 'Invalid response length',
  'no_connection': 'No connection',
  'serial_port_busy': 'COM port is busy (in use by another application)',
  'serial_port_unavailable': 'COM port unavailable',
  'successful_execution_of_command': 'Command executed successfully',
  "unknown_command_invalid_packet_format_or_unknown_parameters":
      "Unknown command, invalid packet format or unknown parameters",
  "invalid_fn_state_requires_different_state":
      "Invalid fiscal storage state. This command requires a different state",
  "fn_error_request_extended_details":
      "Fiscal storage error. Request extended details",
  "ks_error_request_extended_details":
      "Cryptographic processor error. Request extended details",
  "fn_service_life_expired": "Fiscal storage service life expired",
  "fn_archive_full": "Fiscal storage archive full",
  "invalid_date_or_time_logic":
      "Invalid date and/or time. Operation date and time do not match fiscal storage logic",
  "requested_data_not_found_in_fn_archive":
      "Requested data not found in fiscal storage archive",
  "incorrect_command_parameter_value":
      "Incorrect command parameter value. Parameters have correct format but invalid value",
  "tlv_data_size_exceeded_limit": "TLV data size exceeded limit",
  "no_transport_connection_establish_ofd":
      "No transport connection. Establish a connection with OFD and send the 'Transport connection with OFD' command",
  "crypto_coprocessor_resource_exhausted":
      "Cryptographic coprocessor resource exhausted. Fiscal mode must be closed",
  "ofd_storage_resource_exhausted": "OFD storage resource exhausted",
  "message_queue_waiting_resource_exhausted":
      "Message queue waiting resource exhausted (old message over 30 days)",
  "shift_duration_exceeds_24_hours": "Shift duration exceeds 24 hours",
  "time_difference_exceeds_5_minutes":
      "Invalid time difference between operations (more than 5 minutes)",
  "ofd_message_cannot_be_accepted":
      "OFD message cannot be accepted (extended response data indicates reason)",
  "client_payment_less_than_receipt_total":
      "Amount paid by client is less than receipt total",
  "cannot_cancel_previous_command": "Cannot cancel previous command",
  "cash_register_zeroed_repeat_closure_impossible":
      "Cash register zeroed (repeat closing impossible)",
  "section_total_less_than_void_amount":
      "Section receipt total is less than void amount",
  "insufficient_funds_in_kkt_for_payout":
      "Insufficient funds in cash register for payout",
  "kkt_locked_awaiting_tax_inspector_password":
      "Cash register locked awaiting tax inspector password",
  "general_closing_required": "General closing required",
  "incorrect_command_parameters": "Incorrect command parameters",
  "no_data_available": "No data",
  "invalid_parameter_under_current_settings":
      "Invalid parameter under current settings",
  "command_parameters_unsupported_in_this_implementation":
      "Command parameters unsupported in this implementation",
  "command_not_supported_in_this_implementation":
      "Command not supported in this implementation",
  "rom_error": "ROM error",
  "internal_kkt_software_error": "Internal KKT software error",
  "shift_surcharge_accumulation_overflow":
      "Surcharge accumulation overflow in shift",
  "general_accumulation_overflow": "General accumulation overflow in shift",
  "shift_open_operation_not_allowed": "Shift open – operation impossible",
  "shift_not_open_operation_not_allowed":
      "Shift not open – operation impossible",
  "section_accumulation_overflow": "Section accumulation overflow in shift",
  "discount_accumulation_overflow": "Discount accumulation overflow in shift",
  "discount_range_overflow": "Discount range overflow",
  "cash_payment_range_overflow": "Cash payment range overflow",
  "payment_type_2_range_overflow": "Payment type 2 range overflow",
  "payment_type_3_range_overflow": "Payment type 3 range overflow",
  "payment_type_4_range_overflow": "Payment type 4 range overflow",
  "sum_of_all_payment_types_less_than_receipt_total":
      "Sum of all payment types less than receipt total",
  "insufficient_cash_in_drawer": "Insufficient cash in drawer",
  "tax_accumulation_overflow": "Tax accumulation overflow in shift",
  "receipt_total_overflow": "Receipt total overflow",
  "operation_not_allowed_in_open_receipt_of_this_type":
      "Operation not allowed in open receipt of this type",
  "open_receipt_operation_not_allowed": "Receipt open – operation impossible",
  "check_buffer_overflow": "Check buffer overflow",
  "tax_turnover_accumulation_overflow":
      "Tax turnover accumulation overflow in shift",
  "non_cash_payment_exceeds_receipt_total":
      "Non-cash payment exceeds receipt total",
  "shift_exceeds_24_hours": "Shift exceeds 24 hours",
  "invalid_password": "Invalid password",
  "printing_previous_command_results": "Printing previous command results",
  "cash_accumulation_overflow": "Cash accumulation overflow in shift",
  "payment_type_2_accumulation_overflow":
      "Payment type 2 accumulation overflow in shift",
  "payment_type_3_accumulation_overflow":
      "Payment type 3 accumulation overflow in shift",
  "payment_type_4_accumulation_overflow":
      "Payment type 4 accumulation overflow in shift",
  "receipt_closed_operation_not_allowed":
      "Receipt closed – operation impossible",
  "no_document_to_repeat": "No document to repeat",
  "awaiting_continue_print": "Waiting for continue print command",
  "document_opened_by_other_cashier": "Document opened by another cashier",
  "discount_exceeds_accumulation": "Discount exceeds accumulation in receipt",
  "markup_range_exceeded": "Markup range exceeded",
  "voltage_24v_dropped": "24V voltage dropped",
  "table_not_defined": "Table not defined",
  "invalid_operation": "Invalid operation",
  "negative_receipt_total": "Negative receipt total",
  "overflow_on_multiplication": "Overflow on multiplication",
  "price_range_exceeded": "Price range exceeded",
  "quantity_range_exceeded": "Quantity range exceeded",
  "department_range_exceeded": "Department range exceeded",
  "insufficient_section_funds": "Insufficient section funds",
  "section_funds_overflow": "Section funds overflow",
  "insufficient_tax_turnover": "Insufficient tax turnover",
  "tax_turnover_overflow": "Tax turnover overflow",
  "i2c_power_error": "Power error during I2C response",
  "no_check_paper": "No receipt paper",
  "no_journal_paper": "No journal paper",
  "insufficient_tax_funds": "Insufficient tax funds",
  "tax_funds_overflow": "Tax funds overflow",
  "payout_overflow_in_shift": "Payout overflow in shift",
  "cutter_error": "Cutter error",
  "unsupported_in_submode": "Command not supported in this submode",
  "unsupported_in_mode": "Command not supported in this mode",
  "ram_error": "RAM error",
  "power_supply_error": "Power supply error",
  "printer_tach_error": "Printer error: no tachogenerator pulses",
  "printer_sensor_error": "Printer error: no sensor signal",
  "firmware_replacement": "Firmware replacement",
  "field_not_editable": "Field not editable",
  "hardware_error": "Hardware error",
  "date_mismatch": "Date mismatch",
  "invalid_date_format": "Invalid date format",
  "invalid_length_field": "Invalid value in length field",
  "receipt_total_range_overflow": "Receipt total range overflow",
  "cash_overflow": "Cash overflow",
  "shift_income_overflow": "Shift income overflow",
  "shift_outcome_overflow": "Shift outcome overflow",
  "shift_return_income_overflow": "Shift return income overflow",
  "shift_return_outcome_overflow": "Shift return outcome overflow",
  "check_markup_overflow": "Check markup overflow",
  "check_discount_overflow": "Check discount overflow",
  "negative_markup_total": "Negative markup total",
  "negative_discount_total": "Negative discount total",
  "zero_receipt_total": "Zero receipt total",
  "cash_register_not_registered": "Cash register not registered",
  "field_size_exceeded": "Field size exceeded",
  "print_field_overflow": "Print field overflow with current font settings",
  "field_overlap": "Field overlap",
  "ram_restore_success": "RAM restore successful",
  "receipt_operation_limit_exhausted": "Receipt operation limit exhausted",
  "perform_shift_closure_report": "Perform shift closure report",
  "invalid_action": "Invalid action",
  "item_not_found_in_database": "Item not found in goods database",
  "invalid_item_record_data": "Invalid data in item record in goods database",
  "invalid_database_file_size":
      "Invalid size of goods database or registers file",
  "datetime_control_error": "Date and time control (confirm date and time)",
  "power_supply_voltage_exceeded": "Power supply voltage exceeded",
  "shift_numbers_mismatch": "Shift numbers mismatch",
  "slip_buffer_empty": "Slip buffer empty",
  "slip_document_not_present": "Slip document not present",
  "field_not_editable_in_this_mode": "Field not editable in this mode",
  "printer_connection_lost":
      "No connection with printer or no tachometer pulses",
  "printhead_overheat": "Printhead overheat",
  "temperature_out_of_range": "Temperature out of range",
  "invalid_receipt_subtotal": "Invalid receipt subtotal",
  "minimum_free_memory_limit_exceeded": "Minimum free memory limit exceeded",
  "invalid_date_clock_reset": "Invalid date (Clock reset? Set the date!)",
  "journal_report_not_printed": "Journal report not printed!",
  "buffer_empty": "Buffer empty",
  "critical_load_error_errxx": "Critical error while loading ERRxx",
  "bill_acceptor_connection_error": "Bill acceptor connection error",
  "bill_acceptor_busy": "Bill acceptor busy",
  "receipt_total_mismatch_with_bill_acceptor":
      "Receipt total mismatch with bill acceptor",
  "bill_acceptor_error": "Bill acceptor error",
  "bill_acceptor_nonzero_total": "Bill acceptor total is not zero",
};

/// Mapping of numeric error codes to keys.
const Map<int, String> _codeMap = {
  -19: 'protection_key_not_found',
  -18: 'port_blocked',
  -17: 'port_not_open',
  -16: 'failed_to_connect_to_server',
  -15: 'cannot_change_baudrate_in_trk',
  -14: 'cannot_remove_active_logical_device',
  -13: 'check_subtotal_not_changed',
  -12: 'not_supported_in_this_driver_version',
  -11: 'protocol_error',
  -10: 'invalid_logical_device_number',
  -9: 'parameter_out_of_range',
  -8: 'unrecognized_error',
  -7: 'invalid_response_length',
  -6: 'no_connection',
  -5: 'no_connection',
  -4: 'no_connection',
  -3: 'serial_port_busy',
  -2: 'serial_port_unavailable',
  -1: 'no_connection',
  0: 'successful_execution_of_command',
  1: 'unknown_command_invalid_packet_format_or_unknown_parameters',
  2: 'invalid_fn_state_requires_different_state',
  3: 'fn_error_request_extended_details',
  4: 'ks_error_request_extended_details',
  5: 'fn_service_life_expired',
  6: 'fn_archive_full',
  7: 'invalid_date_or_time_logic',
  8: 'requested_data_not_found_in_fn_archive',
  9: 'incorrect_command_parameter_value',
  16: 'tlv_data_size_exceeded_limit',
  17: 'no_transport_connection_establish_ofd',
  18: 'crypto_coprocessor_resource_exhausted',
  20: 'ofd_storage_resource_exhausted',
  21: 'message_queue_waiting_resource_exhausted',
  22: 'shift_duration_exceeds_24_hours',
  23: 'time_difference_exceeds_5_minutes',
  32: 'ofd_message_cannot_be_accepted',
  38: 'client_payment_less_than_receipt_total',
  43: 'cannot_cancel_previous_command',
  44: 'cash_register_zeroed_repeat_closure_impossible',
  45: 'section_total_less_than_void_amount',
  46: 'insufficient_funds_in_kkt_for_payout',
  48: 'kkt_locked_awaiting_tax_inspector_password',
  50: 'general_closing_required',
  51: 'incorrect_command_parameters',
  52: 'no_data_available',
  53: 'invalid_parameter_under_current_settings',
  54: 'command_parameters_unsupported_in_this_implementation',
  55: 'command_not_supported_in_this_implementation',
  56: 'rom_error',
  57: 'internal_kkt_software_error',
  58: 'shift_surcharge_accumulation_overflow',
  59: 'general_accumulation_overflow',
  60: 'shift_open_operation_not_allowed',
  61: 'shift_not_open_operation_not_allowed',
  62: 'section_accumulation_overflow',
  63: 'discount_accumulation_overflow',
  64: 'discount_range_overflow',
  65: 'cash_payment_range_overflow',
  66: 'payment_type_2_range_overflow',
  67: 'payment_type_3_range_overflow',
  68: 'payment_type_4_range_overflow',
  69: 'sum_of_all_payment_types_less_than_receipt_total',
  70: 'insufficient_cash_in_drawer',
  71: 'tax_accumulation_overflow',
  72: 'receipt_total_overflow',
  73: 'operation_not_allowed_in_open_receipt_of_this_type',
  74: 'open_receipt_operation_not_allowed',
  75: 'check_buffer_overflow',
  76: 'tax_turnover_accumulation_overflow',
  77: 'non_cash_payment_exceeds_receipt_total',
  78: 'shift_exceeds_24_hours',
  79: 'invalid_password',
  80: 'printing_previous_command_results',
  81: 'cash_accumulation_overflow',
  82: 'payment_type_2_accumulation_overflow',
  83: 'payment_type_3_accumulation_overflow',
  84: 'payment_type_4_accumulation_overflow',
  85: 'receipt_closed_operation_not_allowed',
  86: 'no_document_to_repeat',
  88: 'awaiting_continue_print',
  89: 'document_opened_by_other_cashier',
  90: 'discount_exceeds_accumulation',
  91: 'markup_range_exceeded',
  92: 'voltage_24v_dropped',
  93: 'table_not_defined',
  94: 'invalid_operation',
  95: 'negative_receipt_total',
  96: 'overflow_on_multiplication',
  97: 'price_range_exceeded',
  98: 'quantity_range_exceeded',
  99: 'department_range_exceeded',
  101: 'insufficient_section_funds',
  102: 'section_funds_overflow',
  104: 'insufficient_tax_turnover',
  105: 'tax_turnover_overflow',
  106: 'i2c_power_error',
  107: 'no_check_paper',
  108: 'no_journal_paper',
  109: 'insufficient_tax_funds',
  110: 'tax_funds_overflow',
  111: 'payout_overflow_in_shift',
  113: 'cutter_error',
  114: 'unsupported_in_submode',
  115: 'unsupported_in_mode',
  116: 'ram_error',
  117: 'power_supply_error',
  118: 'printer_tach_error',
  119: 'printer_sensor_error',
  120: 'firmware_replacement',
  122: 'field_not_editable',
  123: 'hardware_error',
  124: 'date_mismatch',
  125: 'invalid_date_format',
  126: 'invalid_length_field',
  127: 'receipt_total_range_overflow',
  132: 'cash_overflow',
  133: 'shift_income_overflow',
  134: 'shift_outcome_overflow',
  135: 'shift_return_income_overflow',
  136: 'shift_return_outcome_overflow',
  137: 'shift_surcharge_accumulation_overflow',
  138: 'check_markup_overflow',
  139: 'check_discount_overflow',
  140: 'negative_markup_total',
  141: 'negative_discount_total',
  142: 'zero_receipt_total',
  143: 'cash_register_not_registered',
  144: 'field_size_exceeded',
  145: 'print_field_overflow',
  146: 'field_overlap',
  147: 'ram_restore_success',
  148: 'receipt_operation_limit_exhausted',
  150: 'perform_shift_closure_report',
  155: 'invalid_action',
  156: 'item_not_found_in_database',
  157: 'invalid_item_record_data',
  158: 'invalid_database_file_size',
  192: 'datetime_control_error',
  194: 'power_supply_voltage_exceeded',
  196: 'shift_numbers_mismatch',
  197: 'slip_buffer_empty',
  198: 'slip_document_not_present',
  199: 'field_not_editable_in_this_mode',
  200: 'printer_connection_lost',
  201: 'printhead_overheat',
  202: 'temperature_out_of_range',
  203: 'invalid_receipt_subtotal',
  206: 'minimum_free_memory_limit_exceeded',
  207: 'invalid_date_clock_reset',
  208: 'journal_report_not_printed',
  209: 'buffer_empty',
  213: 'critical_load_error_errxx',
  224: 'bill_acceptor_connection_error',
  225: 'bill_acceptor_busy',
  226: 'receipt_total_mismatch_with_bill_acceptor',
  227: 'bill_acceptor_error',
  228: 'bill_acceptor_nonzero_total',
};

/// Returns the error key for the given numeric [code].
String getErrorKey(int code) {
  return _codeMap[code] ?? 'unknown_error_code';
}

/// Returns a localized error message for the given numeric [code].
String errorMessage(int code) {
  final key = getErrorKey(code);
  return errorsKKM[key] ?? 'Unknown error ($code)';
}
